### ISSUE TITLE
Complete rewrite of tool

### ISSUE THREAD

**Issue by mbsck** [Matisse-Consortium/p2obp#25]
Accomodate immediate upload and cut out the intermediate steps (e.g., OB-creation and such).
Make it still possible to also create the OBs simultaneously, as a safeguard however

Include in this the following

- [x] Direct OB-creation and upload (cutting the upload and ob-creation script-middle men out), thus improving the upload and making it easier able to bugtest as well as add new functionality
- [x] If a SCI-cannot be determined (fix the parser Error)
- [x] If an OB cannot be created make sth that avoids that
- [x] Declutter the code in general
- [x] Implement datasets for the Guide Stars
- [x] Implement Template datasets
- [x] Implement datasets for better coordinate info on certain stars

**Comment by MBSck** [comment]
Include in this the following

- [ ] Direct OB-creation and upload (cutting the upload and ob-creation script-middle men out), thus improving the upload and making it easier able to bugtest as well as add new functionality
- [ ] Declutter the code in general
- [ ] Implement datasets for the Guide Stars
- [ ] Implement Template datasets
- [ ] Implement datasets for better coordinate info on certain stars

**Comment by mbsck** [comment]
All implemented with the last pushes
